### ISSUE TITLE
Newest tag breaks builds

### ISSUE THREAD

**Issue by lchrusciel** [FriendsOfBehat/ContextServiceExtension#17]
After update following error starts displaying: 
![zrzut ekranu 2017-12-22 o 18 20 08](https://user-images.githubusercontent.com/6213903/34306693-cd1abbba-e744-11e7-98d2-865a1668980c.png)

The core of the problem is that https://github.com/FriendsOfBehat/ContextServiceExtension/blob/master/src/Context/Environment/Handler/ContextServiceEnvironmentHandler.php#L46 is not initialized and a null value is not valid for foreach loop https://github.com/FriendsOfBehat/ContextServiceExtension/blob/master/src/Context/Environment/Handler/ContextServiceEnvironmentHandler.php#L154.

The problem occurs when there are no initializers at all.

**Comment by pamil** [comment]
Solved by #18, tag incoming soon.

**Comment by pamil** [comment]
v1.1.1 released!
