### ISSUE TITLE
Autoconfigure/Autowire: how to use with shared container ?

### ISSUE THREAD

**Issue by tristanbes** [FriendsOfBehat/ContextServiceExtension#23]
Hello,

Trying to migrate a legacy application where we had:

```xml
<service id="features.actions.article" class="Features\Actions\ArticleActions">
        <argument type="service" id="__symfony__.Bundle\Admin\ArticleBundle\Manager\ArticleManager" />
        <argument type="service" id="features.service.shared_storage" />
        <argument type="service" id="__symfony__.security.authorization_checker" />
        <argument type="service" id="__symfony__.validator" />
        <tag name="fob.context_service" />
</service>
```

Gives now the `The "Bundle\Admin\ArticleBundle\Manager\ArticleManager" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.`

Which is normal because the service are now no longer public.

So how to use it without making all service public again ? 
do you have an idea @pamil ?

Thanks

**Comment by tristanbes** [comment]
anyone ?

**Comment by pamil** [comment]
For now, the only way is to make it public until we got a better solution.

**Comment by tristanbes** [comment]
Do you had time to think about a possible solution ?

**Comment by pamil** [comment]
@tristanbes FriendsOfBehat/SymfonyExtension v2 would solve your issue :) Docs are in progress, but basically, contexts creation is moved to Symfony application container, so both autowiring, autoconfiguring and referencing private services works fine. See https://github.com/Sylius/Sylius/pull/10056 for changes needed to migrate Sylius to v2.

**Comment by pamil** [comment]
Should be released this or the next week.
